#
#  Author: Fall Lewis YOMBA
#  Date: 2023-06-12 22:01:35 +0100 (Mon, 12 Jun 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                   R a n c h e r   K u s t o m i z a t i o n
# ============================================================================ #

# https://artifacthub.io/packages/helm/rancher-stable/rancher

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# override namespace for all resources
# may cause duplicate namespace clashes if different namespaces are defined in bases
#namespace: cattle-system # XXX: Do not set this if using remote base or Helm charts - may override creating roles for kube-system for leader election etc. eg. for Cert Manager

resources:
  - namespace.yaml
  #- ../../cert-manager/base

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/latest
    version: 2.7.9
    releaseName: rancher
    namespace: cattle-system
    includeCRDs: true
    valuesFile: values.yaml
