#
#  Author: Fall Lewis YOMBA
#  Date: 2021-11-29 16:09:45 +0000 (Mon, 29 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#          P r o m e t h e u s   S t a c k   K u s t o m i z a t i o n
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: prometheus  # Do not override helm chart, can cause issues

resources:
  - namespace.yaml

# done in namespace yaml now
#patchesStrategicMerge:
#  - goldilocks-namespace-enable.patch.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    #version: 21.0.0
    version: 45.10.1
    releaseName: kube-prometheus-stack
    namespace: prometheus
    includeCRDs: true
    valuesFile: values.yaml

# XXX: ArgoCD specific workaround for:
#
#   CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
#
#     https://github.com/argoproj/argo-cd/issues/8128
#
patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
