#
#  Author: Fall Lewis YOMBA
#  Date: [% DATE  # 2020-02-13 12:54:31 +0000 (Thu, 13 Feb 2020) %]
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                   P o d   D i s r u p t i o n   B u d g e t
# ============================================================================ #

# https://kubernetes.io/docs/tasks/run-application/configure-pdb/

# https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

# https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1/

# https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/

---
#apiVersion: policy/v1beta1  # Kubernetes v1.5+
apiVersion: policy/v1      # Kubernetes v1.21+
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
  namespace: NAMESPACE
spec:
  # minAvailable and maxUnavailable are mutually exclusive - both round up, so minAvailable is safer as maxUnavailable may round up and exceed your expectations
  #minAvailable: 4      # < 1.7  - must calculate yourself, eg 2/3, or 4/5
  minAvailable: 51%     # XXX: Safer than maxUnavailable due to rounding up to more pod replicas
  #maxUnavailable: 25%  # 1.7+ - XXX: do not set to integers, you may cause outages if replicas <= maxUnavailable, and may exceed percentages due to rounding up replicas to take down
  selector:
    matchLabels:
      app: zookeeper
