#
#  Author: Fall Lewis YOMBA
#  Date: [% DATE  # 2020-02-16 18:49:48 +0000 (Sun, 16 Feb 2020) %]
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                             R o l e B i n d i n g
# ============================================================================ #

# https://kubernetes.io/docs/reference/access-authn-authz/rbac/

# https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/role-binding-v1/

# https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/cluster-role-binding-v1/

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: NAME
  namespace: NAMESPACE
subjects:
  - kind: User
    name: MYUSER
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: MYGROUP
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: APP-svc-account
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
