#
#  Author: Fall Lewis YOMBA
#  Date: [% DATE  # 2022-07-28 14:55:09 +0100 (Thu, 28 Jul 2022) %]
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                   B i t n a m i   S e a l e d   S e c r e t
# ============================================================================ #

# https://github.com/bitnami-labs/sealed-secrets

# Generate this from:
#
#   kubeseal -o yaml < secret.yaml > sealed-secret.yaml

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: NAME
  namespace: NAMESPACE
spec:
  encryptedData:
    .dockerconfigjson: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
  template:
    type: kubernetes.io/dockerconfigjson
    # this is an example of labels and annotations that will be added to the output secret
    metadata:
      labels:
        "jenkins.io/credentials-type": usernamePassword
      annotations:
        "jenkins.io/credentials-description": credentials from Kubernetes
