#
#  Author: Fall Lewis YOMBA
#  Date: 2021-04-26 12:20:37 +0100 (Mon, 26 Apr 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#            M u l t i - C l u s t e r   S e r v i c e   o n   G K E
# ============================================================================ #

# Use with Multi-Cluster Ingress - see mci.yaml

# https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-services

# https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress

---
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: APP-mcs
  namespace: NAMESPACE
spec:
  template:
    spec:
      selector:
        app: APP
      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 8080
