#
#  Author: Fall Lewis YOMBA
#  Date: [% DATE  # 2019-11-27 12:19:45 +0000 (Wed, 27 Nov 2019) %]
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                 V e r t i c a l   P o d   A u t o s c a l e r
# ============================================================================ #

# https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler

# https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler

# https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling


# XXX: consider deploying Goldilocks instead - pre-existing VPAs may clash and not appear in the UI - see goldilocks*.yaml


# XXX: Tip: deploy in "Off" mode to get resource request recommendations via:
#
#   kubectl describe vpa APP-vpa
#     or
#   kubectl get vpa APP-vpa --output yaml
#

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: APP-vpa
  namespace: NAMESPACE
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: APP-deployment
  updatePolicy:
    updateMode: 'Off'  # setting this to Auto or Recreate may cause downtime and requires pods to be recreated, be careful with pods that take several minutes to come up (eg. web apps that preload cache before becoming ready)
    #updateMode: Initial  # only sets resources at creation time, never updates / cycles pods later
#    updateMode:  Auto  # same as Recreate but may take advantage of restart-free updates at a later date
#    containerPolicies:
#      - containerName: '*'
#        minAllowed:
#          cpu: 100m
#          memory: 100Mi
#        maxAllowed:
#          cpu: 1
#          memory: 500Mi
#        controlledResources: ["cpu", "memory"]
#        controlledValues: RequestsAndLimits
#      # switch it off for this sidecar
#      - containerName: my-sidecar
#        mode: "Off"
#      - containerName: istio-proxy
#        mode: "Off"
