#
#  Author: Fall Lewis YOMBA
#  Date: 2021-10-28 16:19:18 +0100 (Thu, 28 Oct 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#            M e t r i c s   S e r v e r   K u s t o m i z a t i o n
# ============================================================================ #

# Quick way of getting Metrics Server on Kubernetes on Docker Desktop for testing HPA/VPA

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system  # XXX: 3 objects without explicit namespace as shown by kustomize_check_objects_namespaces.sh in the adjacent DevOps Bash tools repo

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: --kubelet-insecure-tls  # because Docker Desktop K8s doesn't have an SSL cert supporting its private IP address that the metric server is scraping metrics from the API
