#
#  Author: Fall Lewis YOMBA
#  Date: 2022-03-09 18:41:33 +0000 (Wed, 09 Mar 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                  K e y c l o a k   K u s t o m i z a t i o n
# ============================================================================ #

# https://artifacthub.io/packages/helm/bitnami/keycloak

# https://github.com/bitnami/bitnami-docker-keycloak

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: 14.2.0
    releaseName: keycloak
    namespace: keycloak
    includeCRDs: true
    valuesFile: values.yaml

# Chart upgrades may upgrade the PostgreSQL version resulting in this error:
#
#     postgresql 16:29:50.81 INFO  ==> ** Starting PostgreSQL **
#     2023-04-14 16:29:50.825 GMT [1] FATAL:  database files are incompatible with server
#     2023-04-14 16:29:50.825 GMT [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 15.2.
#
# Better solution is to manage PostgreSQL externally though
#
#patches:
#  - path: keycloak-postgresql-version.patch.yaml
#    target:
#      group: apps
#      version: v1
#      kind: StatefulSet
#      name: keycloak-postgresql
#      namespace: keycloak
