#
#  Author: Fall Lewis YOMBA
#  Date: 2023-05-06 03:19:42 +0100 (Sat, 06 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                      M e t a l   L B   N a m e s p a c e
# ============================================================================ #

---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    # XXX: required for Pod Security Admission in Kubernetes 1.23+
    # https://metallb.universe.tf/installation/
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
