#
#  Author: Fall Lewis YOMBA
#  Date: 2021-12-06 12:34:38 +0000 (Mon, 06 Dec 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                          P o l a r i s   V a l u e s
# ============================================================================ #

# helm repo add fairwinds-stable https://charts.fairwinds.com/stable
#
# helm show values fairwinds-stable/polaris >> polaris-values.yaml

---
# config -- The (polaris configuration)[https://github.com/FairwindsOps/polaris#configuration]. If not provided then the (default)[https://github.com/FairwindsOps/polaris/blob/master/examples/config.yaml] config from Polaris is used.
config: null

dashboard:
  resources:
    requests:
      cpu: 100m      # default upstream
      memory: 256Mi  # default: 128Mi
    limits:
      cpu: 150m      # default upstream
      memory: 512Mi  # default upsream
