#
#  Author: Fall Lewis YOMBA
#  Date: 2021-06-01 16:37:54 +0100 (Tue, 01 Jun 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                  F l u x C D   v 2   S l a c k   A l e r t s
# ============================================================================ #

# https://fluxcd.io/docs/guides/notifications/

# 1. Create Slack alert provider as per instructions in fluxcd-slack-provider.yaml
#
# 2. Apply this manifest:
#
#       kubectl apply -f fluxcd-slack-alerts.yaml
#
# 3. Verify:
#
#       flux get alerts


# Creates alerts for everything
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: repo-kustomizations
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
