#
#  Author: Fall Lewis YOMBA
#  Date: 2023-04-29 03:04:49 +0100 (Sat, 29 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                   F l u x C D v 2   H e l m   R e l e a s e
# ============================================================================ #

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: ">=23.0.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: traefik-values.yaml
      optional: true
  interval: 1h
  releaseName: traefik
  targetNamespace: traefik
