#
#  Author: Fall Lewis YOMBA
#  Date: 2021-05-28 18:16:27 +0100 (Fri, 28 May 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                F l u x C D v 2   G i t   /   H e l m   r e p o
# ============================================================================ #

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
#kind: HelmRepository
metadata:
  # XXX: Edit
  name: NAME
  namespace: flux-system
spec:
  interval: 1m
  ref:
    # XXX: Edit
    branch: master
  # XXX: Edit
  # Git repository
  url: https://github.com/fallewi/Kubernetes-configs
  # Helm repository
  # url: https://helm.traefik.io/traefik
