#
#  Author: Fall Lewis YOMBA
#  Date: 2020-02-13 12:54:31 +0000 (Thu, 13 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#   C l o u d   S Q L   P r o x y   P o d   D i s r u p t i o n   B u d g e t
# ============================================================================ #

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloud-sql-proxy
  namespace: NAMESPACE
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app: cloud-sql-proxy
