#
#  Author: Fall Lewis YOMBA
#  Date: 2022-08-19 16:12:48 +0100 (Fri, 19 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#    B e a t s   o n   E l a s t i c   C l o u d   o n   K u b e r n e t e s
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elasticsearch

resources:
  # don't run this in GitOps / ArgoCD - it'll likely repeatedly replace the caBundle
  #- ../elastic-cloud  # should contain elastic-cloud-*.yaml
  - namespace.yaml  # should already be applied from elasticsearch-kustomization.yaml
  - elastic-cloud-beats.yaml
