#
#  Author: Fall Lewis YOMBA
#  Date: 2023-04-07 22:49:16 +0100 (Fri, 07 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#               Kong Cluster Plugin - Request Transformer Advanced
# ============================================================================ #

---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
plugin: request-transformer-advanced
metadata:
  name: global-request-transform-adv
  annotations:
    kubernetes.io/ingress.class: kong
config:
  add:
    headers:
      - X-Kong-Test-Request-Header:MyRequestHeader
  rename:
    headers:
      - User-Agent:My-User-Agent
