#
#  Author: Fall Lewis YOMBA
#  Date: 2022-08-18 17:54:32 +0100 (Thu, 18 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#                                  Chart Values
# ============================================================================ #

# helm repo add elastic https://helm.elastic.co
#
# helm show values elastic/eck-operator >> elastic-cloud-values.yaml

---
#replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 150Mi
  limits:
    cpu: 1
    memory: 1Gi
