#
#  Author: Fall Lewis YOMBA
#  Date: 2023-06-16 02:20:50 +0100 (Fri, 16 Jun 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/fallewi/Kubernetes-configs
#
#  License: see accompanying Fall Lewis YOMBA LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/fall-lewis-yomba-034589123
#

# ============================================================================ #
#         J F r o g   A r t i f a c t o r y   K u s t o m i z a t i o n
# ============================================================================ #

# https://artifacthub.io/packages/helm/jfrog/artifactory-oss

# initial creds are admin/password, will force you to enter a password with strength policy

# The "Open Source" Freemium version is severely neutred and limited to only Generic, Gradle, Ivy and Maven repos
#
# If you want any of the modern languages like Python, or Docker etc then you need to pay for one of the following

# Require licenses:
#
# https://artifacthub.io/packages/helm/jfrog/artifactory
#
# https://artifacthub.io/packages/helm/jfrog/artifactory-ha
#
# https://artifacthub.io/packages/helm/jfrog/jfrog-platform

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: artifactory-oss  # 15 objects not namespaced otherwise

resources:
  - namespace.yaml

helmCharts:
  - name: artifactory-oss
    repo: https://charts.jfrog.io
    version: 107.59.9
    releaseName: artifactory-oss
    namespace: artifactory-oss
    includeCRDs: true
    valuesFile: values.yaml
